project:
  root: "D:/projets/credit_card_fraud_detection"

data:
  root: data 
  raw: raw
  processed: processed

models:
  root: models

reports:
  root: reports
  search: search
  training: training